In [1]:
import pandas as pd
import re
from utils.read_parquet import read_actions, read_balances, read_general_information, read_payments
from features.form_time_features import extract_payment_features
from features.complex_features import calculate_complex_features, calculate_complex_features_actions_based

In [2]:
payments = read_payments()
balances = read_balances()
actions = read_actions()
gen_info = read_general_information()

In [3]:
pay_features = extract_payment_features(payments, k_months=3, current_date=pd.Timestamp("2025-08-31"))
pay_features

            ЛС  Дней_с_последнего_платежа  Платежей_за_последние_3_мес
0           15                          4                            3
1           16                         17                            3
2           17                         17                            3
3           18                         14                            3
4           20                         11                            3
...        ...                        ...                          ...
120244  147099                         27                            2
120245  147100                         18                            3
120246  147101                         18                            3
120247  147102                         22                            3
120248  147103                        102                            0

[120249 rows x 3 columns]

In [26]:
complex = calculate_complex_features(payments, balances, 3, curr_date=pd.Timestamp("2025-08-31"))
complex

,ЛС,Days_Since_Clearance,Payment_Fraction_12M,Consecutive_Debt_Months,Payment_Accrual_Ratio_kM,Balance_Trend_Slope_kM,Current_Debt,Debt_to_Avg_Accrual_3M,Days_Since_Advance_5th,Days_Since_Salary_20th
0,1,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
1,2,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
2,3,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
3,4,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
4,5,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
...,...,...,...,...,...,...,...,...,...,...
150782,150817,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150783,150818,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150784,150819,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150785,150820,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150786,150821,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11

In [18]:
actions_mock = complex[["ЛС"]].copy()
actions_mock["Дата"] = pd.Timestamp("2025-08-31")
actions_mock["Дата"] = actions_mock["Дата"].astype("datetime64[ns]")
actions_mock["Мера"] = "Уведомление о введении ограничения"

In [21]:
complex1 = calculate_complex_features_actions_based(payments, balances, actions_mock, 3)
complex1

,ЛС,Дата,Мера,Days_Since_Clearance,Payment_Fraction_12M,Consecutive_Debt_Months,Payment_Accrual_Ratio_kM,Current_Debt,Balance_Trend_Slope_kM,Debt_to_Avg_Accrual_3M,Days_Since_Advance_5th,Days_Since_Salary_20th
0,1,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
1,2,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
2,3,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
3,4,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
4,5,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
...,...,...,...,...,...,...,...,...,...,...,...,...
150782,150817,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150783,150818,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150784,150819,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150785,150820,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11
150786,150821,2025-08-31,Уведомление о введении ограничения,9999.0,0.0,0,1.0,0.0,0.0,0.0,26,11

In [27]:
complex[complex.Current_Debt>0].head()

,ЛС,Days_Since_Clearance,Payment_Fraction_12M,Consecutive_Debt_Months,Payment_Accrual_Ratio_kM,Balance_Trend_Slope_kM,Current_Debt,Debt_to_Avg_Accrual_3M,Days_Since_Advance_5th,Days_Since_Salary_20th
20,21,9999.0,0.000,8,1.000000,2.182988e-14,775.17,775.170000,26,11
23,24,9999.0,0.750,8,1.000000,-2.800000e+03,93525.73,93525.730000,26,11
26,27,9999.0,0.375,8,0.344067,5.628370e+02,3411.22,3.521066,26,11
30,31,195.0,0.125,6,0.000000,5.426690e+02,3287.21,5.945505,26,11
42,43,76.0,0.125,2,1.021934,2.611800e+01,503.74,2.082086,26,11

In [22]:
complex[complex.Current_Debt>0].head()

,ЛС,Days_Since_Clearance,Payment_Fraction_12M,Consecutive_Debt_Months,Payment_Accrual_Ratio_kM,Balance_Trend_Slope_kM,Current_Debt,Debt_to_Avg_Accrual_3M,Days_Since_Advance_5th,Days_Since_Salary_20th
20,21,9999.0,0.000,8,1.000000,2.182988e-14,775.17,775.170000,26,11
23,24,9999.0,0.750,8,1.000000,-2.800000e+03,93525.73,93525.730000,26,11
26,27,9999.0,0.375,8,0.344067,5.628370e+02,3411.22,3.521066,26,11
30,31,195.0,0.125,6,0.000000,5.426690e+02,3287.21,5.945505,26,11
42,43,76.0,0.125,2,1.021934,2.611800e+01,503.74,2.082086,26,11

In [25]:
complex1[complex1.Current_Debt > 0].drop(columns=["Мера","Дата"]).head()

,ЛС,Days_Since_Clearance,Payment_Fraction_12M,Consecutive_Debt_Months,Payment_Accrual_Ratio_kM,Current_Debt,Balance_Trend_Slope_kM,Debt_to_Avg_Accrual_3M,Days_Since_Advance_5th,Days_Since_Salary_20th
20,21,9999.0,0.000,8,1.000000,775.17,-6.014375e-15,775.170000,26,11
23,24,9999.0,0.750,8,1.000000,93525.73,2.442946e+03,93525.730000,26,11
26,27,9999.0,0.375,8,0.252314,3411.22,-1.919804e+02,3.521066,26,11
30,31,195.0,0.125,6,0.000000,3287.21,3.317404e+02,5.945505,26,11
42,43,76.0,0.125,2,0.815888,503.74,-2.681667e+00,2.082086,26,11