In [1]:
import pandas as pd
from general_information import *

In [2]:
general_info = read_general_information()
actions = read_actions()
balances = read_balances()
payments = read_payments()

Временно обрежу все DataFrames.

In [5]:
balances = balances[balances["ЛС"] < 10000]
balances

,ЛС,2025_1_start,2025_1_accr,2025_1_paid,2025_2_start,2025_2_accr,2025_2_paid,2025_3_start,2025_3_accr,2025_3_paid,...,2025_12_paid,2026_1_start,2026_1_accr,2026_1_paid,2026_2_start,2026_2_accr,2026_2_paid,2026_3_start,2026_3_accr,2026_3_paid
0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,2.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,3.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,4.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,5.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,9995.0,0.00,1270.02,0.00,1270.02,1224.91,1270.02,1224.91,961.19,1224.91,...,1002.3,1310.40,1686.96,1311.00,1686.36,1995.84,1686.36,1995.84,1188.00,2000.00
9992,9996.0,-464.98,739.11,0.01,274.12,621.13,739.11,156.14,600.31,621.13,...,756.6,721.50,740.52,721.50,740.52,756.36,740.52,756.36,601.92,756.36
9993,9997.0,-354.31,0.00,0.00,-354.31,0.00,0.00,-354.31,0.00,0.00,...,1.0,-355.31,0.00,0.00,-355.31,0.00,0.00,-355.31,0.00,0.00
9994,9998.0,-10.53,0.00,1.00,-11.53,0.00,1.00,-12.53,0.00,1.00,...,1.0,-1.00,0.00,1.00,-2.00,0.00,0.00,-2.00,0.00,1.00
9995,9999.0,478.86,34.70,478.86,34.70,104.10,34.70,104.10,76.34,104.10,...,0.0,5822.70,6474.60,5822.07,6475.23,9282.24,6475.23,9282.24,7872.48,17154.72

In [6]:
payments = payments[payments["Номер"]<10000]
payments

       Номер Дата оплаты    Сумма  Способ оплаты
0         15  24.01.2025      100            5.0
1         15  25.01.2026     1240            5.0
2         15  25.05.2025   293,96            5.0
3         15  25.06.2025       10            5.0
4         15  26.02.2025   289,56            5.0
...      ...         ...      ...            ...
78761   9999  29.11.2025  5713,68            5.0
78762   9999  30.04.2025        1            NaN
78763   9999  30.10.2025  3151,02            NaN
78764   9999  31.01.2025     34,7            NaN
78765   9999  31.12.2025  5822,07            NaN

[78766 rows x 4 columns]

In [7]:
for key in actions.keys():
    df = actions[key]["data"]
    actions[key]["data"] = df[df["ЛС"] < 10000]
actions

{'Автодозвон': {'limit': 8000,
  'data': 1       ЛС                 Дата
  2       15  2025-11-01 00:00:00
  3       15  2025-12-01 00:00:00
  4       17  2025-04-01 00:00:00
  5       17  2026-03-01 00:00:00
  6       21  2025-01-01 00:00:00
  ...    ...                  ...
  6017  9989  2025-05-01 00:00:00
  6018  9989  2025-05-01 00:00:00
  6019  9989  2025-08-01 00:00:00
  6020  9989  2025-10-01 00:00:00
  6021  9989  2025-10-01 00:00:00

  [6020 rows x 2 columns]},
 'E-mail': {'limit': 'нет ограничений',
  'data': 1       ЛС                 Дата
  2       25  2025-10-01 00:00:00
  3       25  2025-10-01 00:00:00
  4       25  2025-11-01 00:00:00
  5       25  2025-11-01 00:00:00
  6       25  2025-12-01 00:00:00
  ...    ...                  ...
  6770  9989  2025-09-01 00:00:00
  6771  9989  2025-10-01 00:00:00
  6772  9989  2025-10-01 00:00:00
  6773  9989  2026-02-01 00:00:00
  6774  9999  2026-01-01 00:00:00

  [6773 rows x 2 columns]},
 'СМС': {'limit': 2150,
  'data': 1       ЛС                 Дата
  2       15  2025-11-01 00:00:00
  3       15  2025-12-01 00:00:00
  4       25  2025-07-01 00:00:00
  5       25  2025-10-01 00:00:00
  6       27  2025-08-01 00:00:00
  ...    ...                  ...
  2172  9973  2026-02-01 00:00:00
  2173  9973  2026-03-01 00:00:00
  2174  9979  2026-01-01 00:00:00
  2175  9979  2026-03-01 00:00:00
  2176  9989  2025-08-01 00:00:00

  [2175 rows x 2 columns]},
 'Обзвон оператором': {'limit': 1550,
  'data': 1       ЛС                 Дата
  2       24  2025-08-18 00:00:00
  3       25  2025-02-21 00:00:00
  4       25  2025-03-19 00:00:00
  5       25  2025-04-22 00:00:00
  6       25  2025-05-27 00:00:00
  ...    ...                  ...
  2733  9967  2025-09-22 00:00:00
  2734  9979  2026-01-22 00:00:00
  2735  9988  2026-01-22 00:00:00
  2736  9989  2025-09-29 00:00:00
  2737  9989  2025-10-27 00:00:00

  [2736 rows x 2 columns]},
 'Претензия': {'limit': 400,
  'data': 1      ЛС                 Дата
  2      66  2025-01-01 00:00:00
  3     118  2025-01-01 00:00:00
  4    1231  2026-01-01 00:00:00
  5    1231  2026-02-01 00:00:00
  6    1297  2025-12-01 00:00:00
  ..    ...                  ...
  153  9678  2026-02-01 00:00:00
  154  9864  2025-08-01 00:00:00
  155  9864  2026-01-01 00:00:00
  156  9864  2026-02-01 00:00:00
  157  9970  2025-11-01 00:00:00

  [156 rows x 2 columns]},
 'Выезд к абоненту': {'limit': 500,
  'data': 1      ЛС                 Дата
  2      24  2025-11-01 00:00:00
  3      66  2025-10-01 00:00:00
  4      67  2025-11-01 00:00:00
  5     114  2026-01-01 00:00:00
  6     229  2025-06-01 00:00:00
  ..    ...                  ...
  200  9806  2025-08-01 00:00:00
  201  9838  2025-08-01 00:00:00
  202  9838  2026-01-01 00:00:00
  203  9967  2026-01-01 00:00:00
  204  9974  2026-01-01 00:00:00

  [203 rows x 2 columns]},
 'Уведомление о введении ограничения': {'limit': 6200,
  'data': 1       ЛС                 Дата
  2       15  2025-08-26 00:00:00
  3       15  2025-09-26 00:00:00
  4       15  2025-11-26 00:00:00
  5       15  2025-12-26 00:00:00
  6       17  2026-02-26 00:00:00
  ...    ...                  ...
  8869  9989  2025-06-18 00:00:00
  8870  9989  2025-08-26 00:00:00
  8871  9989  2025-09-18 00:00:00
  8872  9992  2025-11-26 00:00:00
  8873  9992  2025-12-26 00:00:00

  [8872 rows x 2 columns]},
 'Ограничение': {'limit': 200,
  'data': 1      ЛС                 Дата
  2      31  2025-09-09 00:00:00
  3      66  2025-02-25 00:00:00
  4      90  2025-09-11 00:00:00
  5     118  2025-04-19 00:00:00
  6     153  2025-07-11 00:00:00
  ..    ...                  ...
  174  9705  2025-08-19 00:00:00
  175  9838  2025-05-15 00:00:00
  176  9861  2025-03-11 00:00:00
  177  9923  2025-04-14 00:00:00
  178  9989  2025-10-29 00:00:00

  [177 rows x 2 columns]},
 'Заявление о выдаче судебного приказа': {'limit': 400,
  'data': 1      ЛС                 Дата
  2      66  2025-07-30 00:00:00
  3      66  2025-07-30 00:00:00
  4      90  2025-11-24 00:00:00
  5      90  2025-11-24 00:00:00
  6     306  2025-09-25 00:00:00
  ..    ...                  ...
  151  9237  2025-10-24 00:00:00
  152  9358  2025-09-02 00:00:00
  153  9358  2025-09-02 00:00:00
  154  9397  2025-03-24 00:00:00
  155  9397  2025-03-24 00:00:00

  [154 rows x 2 columns]},
 'Получение судебного приказа или ИЛ': {'limit': 250,
  'data': 1     ЛС                 Дата
  2     24  2025-02-13 00:00:00
  3     66  2025-10-22 00:00:00
  4     66  2025-10-22 00:00:00
  5     92  2026-02-24 00:00:00
  6    280  2025-03-04 00:00:00
  7    306  2026-02-18 00:00:00
  8    335  2025-12-18 00:00:00
  9    397  2025-07-14 00:00:00
  10   439  2026-02-05 00:00:00
  11   459  2025-07-10 00:00:00
  12   493  2025-02-10 00:00:00
  13   912  2025-02-13 00:00:00
  14   912  2025-08-13 00:00:00
  15  1436  2025-11-26 00:00:00
  16  1676  2025-11-11 00:00:00
  17  2653  2025-11-26 00:00:00
  18  4226  2025-06-05 00:00:00
  19  4696  2025-09-23 00:00:00
  20  4984  2025-06-24 00:00:00
  21  5160  2025-06-24 00:00:00
  22  5169  2025-06-03 00:00:00
  23  5444  2025-06-03 00:00:00
  24  5523  2025-06-03 00:00:00
  25  5526  2025-06-03 00:00:00
  26  5526  2025-12-19 00:00:00
  27  5528  2025-10-27 00:00:00
  28  5533  2025-06-19 00:00:00
  29  5534  2025-12-19 00:00:00
  30  5537  2025-06-04 00:00:00
  31  5540  2025-06-05 00:00:00
  32  5565  2025-06-03 00:00:00
  33  5711  2025-06-03 00:00:00
  34  5762  2025-10-24 00:00:00
  35  6136  2025-06-03 00:00:00
  36  6153  2026-01-21 00:00:00
  37  6262  2026-01-21 00:00:00
  38  6621  2025-12-17 00:00:00
  39  7553  2025-07-10 00:00:00
  40  8036  2025-12-22 00:00:00
  41  8338  2025-06-02 00:00:00
  42  8534  2025-06-04 00:00:00
  43  9349  2025-03-27 00:00:00
  44  9397  2025-06-24 00:00:00
  45  9599  2025-01-16 00:00:00
  46  9687  2025-05-28 00:00:00
  47  9861  2025-11-10 00:00:00}}

In [ ]:
general_info
general_info

,1,Нет,Нет.1,Нет.2,Да,Нет.3,Нет.4,Да.1,Нет.5,Нет.6,Нет.7,Да.2,Нет.8,Нет.9,Нет.10,Нет.11,Нет.12,0ff2d0eb-33d6-4383-a2a0-07c216c28c07
0,2,Нет,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,d8f85b04-021d-4a6b-909f-085b5719180b
1,3,Нет,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,d8f85b04-021d-4a6b-909f-085b5719180b
2,4,Нет,Нет,Нет,Да,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Да,4bbd6cb2-1490-423e-9a26-2dee70ae6cbc
3,5,Нет,Нет,Нет,Да,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,c379bced-5543-4fd4-af5f-7df66476aba1
4,6,Нет,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,d8f85b04-021d-4a6b-909f-085b5719180b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150815,150817,Нет,Нет,Нет,Да,Да,Да,Нет,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,9591160c-688c-4103-a1e0-fa95f93dc5d8
150816,150818,Нет,Нет,Нет,Да,Да,Да,Нет,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,7014d8cd-6fed-4573-a42a-50422e32765a
150817,150819,Нет,Нет,Нет,Да,Да,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,4a393c32-a036-44eb-b1e9-25e5cba06044
150818,150820,Нет,Нет,Нет,Да,Да,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,6867b06c-d419-40df-b343-edfde4f7fa51
150819,150821,Нет,Нет,Нет,Да,Да,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,a03f4bce-000d-47f0-b924-eb503a73c6e0